#variables declaration here
variable "vpc_name" {}
variable "vpc_cidr_block" {}
variable "pub_subnet_count" {}
variable "pub_subnet_cidr_block" {}
variable "azs" {}
variable "pvt_subnet_count" {}
variable "pvt_subnet_cidr_block" {}
variable "aws_region" {}
variable "aws_access_key_id" {}
variable "aws_secret_access_key" {}
